### ISSUE TITLE
remnote vscode: Oucho Gaucho! 🌵 Nothing to round up! 🤠

### ISSUE THREAD

**Issue by Jackiexiao** [robole/vscode-snippets-ranger#2]
![image](https://user-images.githubusercontent.com/18050469/111281394-da803e80-8677-11eb-8c8a-52af29a6b8c2.png)

but it works fine using local vscode

thx for create this plugin!

**Comment by robole** [comment]
Hi @Jackiexiao 

How are you using VS Code remotely? Container? SSH? WSL?

The extension looks at the local filesystem for snippets, so obviously if you have are using a remote method this may mean the snippet files are not local anymore, so it does not find anything!

I'm not very familiar with remote development in VS Code, but I am a bit reluctant to implement something for this if it involves some complicated client-server style logic. 

From a selfish point of view, I wouldnt use this feature, so it wouldnt be a good investment of my time! If you or someone else are interested in this feature, I am open to receive a PR, provided the code is sensible and does not compromise the existing performance.

**Comment by Jackiexiao** [comment]
thx for your reply,

I use VS Code remote (connect to ubuntu), I also think this is an unimportant feature haha
