### ISSUE TITLE
Stuck @ 'Rounding them up!' 😢 

### ISSUE THREAD

**Issue by idusortus** [robole/vscode-snippets-ranger#3]
New PC, well specced. Restarted, reinstalled. 

Win10 Pro, existing project, no custom snippets.

**Comment by robole** [comment]
hi @idusortus 

In VS Code, could you go to the menu and select `Help> About` and tell me the VS Code version info.

Can you run the command with the Debug Console open to see if there is an error message (like below):
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/3703647/118677561-e5e61680-b82e-11eb-99e4-86a9681dfef5.png)

Can you tell me where you have installed VS Code on Windows? Are you admin? Do you run it as a window program (no ssh/remote/wsl)? Is there anything unusual/particular about your setup?

I ran the extension on Windows 10 machine recently and it was fine, but I will take another look to see if there is any issue again.

**Comment by idusortus** [comment]
Hey, @robole  !

Uninstalled ranger, closed VSC, reinstalled ranger, ran round'em up, been running about 6 minutes now.

Ranger version is 0.20.1

"C:\Program Files\Microsoft VS Code\Code.exe"

I'm logged in as admin, running VSC as admin.

All local. My day-to-day dev setup.

winver: 20H2 / build 19042.928 

VSC Ver: 1.56.2

Thanks!

**Comment by robole** [comment]
Hi @idusortus 

Can you open VS Code from the CLI with all extension disabled? 

```bash
code --disable-extensions
```

Run the command again to see.  That will rule out other extensions.

Do you have any user snippets?

I have no issues on my linux machine. I will check on a windows machine soon to see it is not a Windows-specific.

**Comment by idusortus** [comment]
Thanks again. I'll take a look if you want a hand. Otherwise I'm moving on. 

Or... I'll let you know if I give it a try in Linux.

**Comment by robole** [comment]
hi @idusortus 

I tried the extension on a machine with windows 10 pro (recent install and same version as you), I did a fresh installation of VS Code v1.56.2 installed to the same directory as you ("C:\Program Files\Microsoft VS Code\Code.exe") and had no issue.

![windows-os](https://user-images.githubusercontent.com/3703647/119294385-31226f80-bc09-11eb-9e1d-66b072c9df02.png)

![vscode](https://user-images.githubusercontent.com/3703647/119294451-57480f80-bc09-11eb-851d-444ab73d573c.png)

There has to be something unusual with your environment. There is no issue with the extension.

I am closing the issue. If you can identify what it is, feel free to open a new issue.

All the best

**Comment by robole** [comment]
hi @idusortus 

The [Snippets Ranger ](https://marketplace.visualstudio.com/items?itemName=robole.snippets-ranger) extension has been updated recently. I believe your issue could have been when no workspace was open and you ran the command `Snippets Ranger: Show me that dur Range, Partner`. It should be good now. You can try out v1.6 if you are still interested!

All the best
