### ISSUE TITLE
Not loading snippets in view - "Cannot read properties of undefined (reading '0')'" error

### ISSUE THREAD

**Issue by eleach** [robole/vscode-snippets-ranger#9]
Hello,
I love this extension. When I try to open it I now get:

Command 'Snippets Ranger: . . . resulted in an error. Cannot read properties of undefined (reading '0')'

It is stuck on the loading circle an says 'Rounding them up!'

Version 1.5, - 2023-11-10

Thanks

**Comment by eleach** [comment]
I'm away from my computer now. I'll troubleshoot it on my own. Thanks for the quick reply and fun, useful extension. If you can delete this non-issue please do.

**Comment by eleach** [comment]
Hello Rob,

I uninstalled ES7 React snippets and Simple React Snippets. I JSON validated my personal snippets and that is a valid json file. I also temporarily deleted my personal snippets.

I'm still getting the error on both a Linux/Ubuntu machine and on a Mac.

On Ubuntu my vsCode is:

   Version: 1.84.1
   Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
   Date: 2023-11-06T12:35:31.181Z
   Electron: 25.9.2
   ElectronBuildId: 24603566
   Chromium: 114.0.5735.289
   Node.js: 18.15.0
   V8: 11.4.183.29-electron.0
   OS: Linux x64 6.5.6-76060506-generic

vsCode has been more flaky than usual lately with crashing windows.

Thanks

**Comment by robole** [comment]
Thanks for taking the time! It is a strange one! 

I did a major refactor lately and I'm in a better spot to review the error handling and resilience of handling idiosyncrasies around data and environments.  I had [a similar issue](https://github.com/robole/vscode-snippets-ranger/issues/3) reported by a windows user a while back but I didn't have anything concrete to go on. and I needed to refactor to be able to debug things in a saner manner!

Im an Ubuntu user and I haven't encountered crashes!  It might help if you clear your cache: https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai/69704193#69704193 .

Out of curiosity, I installed the same 2 snippets extensions you mentioned and had no issue!

![Kazam_screenshot_00000](https://github.com/robole/vscode-snippets-ranger/assets/3703647/2fb11800-068d-4650-9f2c-aa2e0774e167)

I will review error handling and test a few scenarios. Perhaps I can makes some changes that gives a more informative error!

**Comment by robole** [comment]
I tracked down the issue. When you run the extension when no workspace is open, it throws that error. 

Try to run the command  `Snippets Ranger: Show me that dur Range, Partner` with an open workspace and let me know if it works!

I will push a fix for this scenario.

**Comment by eleach** [comment]
It is working. Version 1.6.0. Thanks again for being so responsive.

**Comment by robole** [comment]
Good! Could you star the repo if you get the chance @eleach ? 

Its nice to have some social proof for a project!
